### ISSUE TITLE
Future forms configuration

### ISSUE THREAD

**Issue by I-Valchev** [bobdenotter/forms#46]
Hi all 

Here's a suggested configuration for a future major release of `bolt/forms`. Please provide any feedback that you may have!

```yaml
## This is default, all forms inherit from here.
default:
    csrf: true
    honeypot: true
    spam-action: mark-as-spam
    template: '@boltforms/form.html.twig'
    layout: 'form_div_layout.html.twig'
    captcha:
        repatcha: ...
        hcaptcha: ...
    
contact:
    csrf: false # here you can override any of the default config
    attr: ?? # Add attributes to form itself?
    content:
        step: 1
        fields: ... # Same as current form
    on_submit:
        save:
            contenttype:
                name: ..
                field_map: ...
            table:
                name: ...
                field_map: ...
        email: # the email is a list, allowing you to send as many emails to as many recipients as you like
            - subject_template: ...
              body_template: ...
              recipients: [ foo@example.org, {FROM_FIELD} ]
              cc_recipients: ...
              bcc_recipients: ...
              attach: [ name of file fields to attach ]
        action:
            redirect: ...
            messages:
                success: ...
                error: ...

```

**Comment by bobdenotter** [comment]
Some other pitfalls we'll need to avoid if we're going to refactor this and introduce breaking changes: 

 - the fields configuration (and primarily the "options" and its "attr" flags) are clearly designed for people who write code, and are not user friendly for end-users who merely want to implement a form. To a large extent this is unavoidable, but we can document it better
 - We should be able to add attributes to the form itself. Like being able to influence the class/id of the form, without having to override the complex Symfony form templates.

**Comment by I-Valchev** [comment]
Some other things to at least consider:

- should there be a standardised way to select forms that belong to a page?
- from builder?

**Comment by I-Valchev** [comment]
Also:
https://wpforms.com/features/

**Comment by I-Valchev** [comment]
- It should be easier, or at the very least documented, how to override the HTML rendering of a specific field, of a field type, etc. Symfony allows that by extending templates and overriding blocks, but given the extra layer of abstraction that is `bolt/forms`, it is difficult.

**Comment by nestordedios** [comment]
@I-Valchev as we discussed, it might be good to have it in the list as well:

- Easy way to override default Boltforms CSS.

**Comment by I-Valchev** [comment]
- Make the `type: date`, `type: datetime` and `type: dateinterval` easier to configure in terms of how it is rendered...
Right now, to render a date with the standard datepicker, it looks like this:

```yaml
date_of_birth:
    type: date
    options:
        widget: single_text
```

Would be much better to have something that is _human comprehendable_, for example:
```yaml
date_of_birth:
    type: date
    variant: datepicker
```

- More generally, see if we can provide "shortcuts" to common symfony/forms options (radio buttons, checkboxes, etc.) rather than asking people to set stuff like `multiple: false` etc..
