### ISSUE TITLE
How I can set values into form?

### ISSUE THREAD

**Issue by jlgranda** [bobdenotter/forms#48]
I need preinitialise some value into form.

**Comment by I-Valchev** [comment]
Hi @jlgranda ,

I believe you can set the following:

```yaml
        email:
            type: email
            options:
                empty_data: 'john@doe.com'
```

Can you confirm if it works? Thanks!
