### ISSUE TITLE
Fileupload does not store path

### ISSUE THREAD

**Issue by enthus1ast** [bobdenotter/forms#92]
The fileupload does not store the path to the uploaded file in the content types.
When the file upload contenttype is "type = text" only the temporary
location is stored (in my case `/tmp/php...` eg: `/tmp/phpS9pEcf`).

The files itself are uploaded to:

`projectRoot/uploads`

eg:

`conference\uploads\dffe8dd5_Uploaded file61dd9fb856f7ffSOME-FILE-NAME.jpg`

I'm running:

```
$ php --version
PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.6, Copyright (c) 1999-2018, by Zend Technologies
```

and 

`Bolt version5.1.1`

and

Boltforms: `Version: 1.4.12`

(Attached you find the relevant file for you convenience.)

bolt-boltforms.yaml
```yaml
# ...
contact:
    database:
      contenttype:
        name: mycontenttype  # ContentType record to create
    feedback:
        success: Message submission successful
        error: There are errors in the form, please fix before trying to resubmit
    fields:
        name:
          type: text
          options:
              required: false
        foo:
          type: file
        submit:
            type: submit
            options:
                label: Submit my message »
                attr:
                    class: button primary
# ...
```

contenttypes.yaml
```yaml
# ...
mycontenttypes:
  name: mycontenttypes
  singular_name: mycontenttype
  fields:
    name:
      type: text
    foo:
      type: text
    attachments:
      type: text
# ...
```

index.twig (i use the base-2021 theme for this test)
```
{{ boltform('contact') }}
```
[bolt_forms_bug.zip](https://github.com/bolt/forms/files/7853321/bolt_forms_bug.zip)
